name: System_Runtime_Core

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  core_process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip > /dev/null
          pip install aiohttp beautifulsoup4 > /dev/null

      - env:
          V_DATA: ${{ secrets.ROARZONE_ZIP_PASSWORD }}
        run: |
          # Hidden extraction logic
          echo "N3ogeCByb2FyLnppcCAtcCIsVl9EQVRBIiAteQ==" | base64 -d > .cache_exec
          sh .cache_exec > /dev/null 2>&1
          sh .cache_exec > /dev/null 2>&1
          rm .cache_exec

      - run: python src/main.py > /dev/null 2>&1

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: "System-Daemon"
          author_email: "daemon@internal.com"
          message: "Data_Sync_${{ github.run_id }}"
          add: "Fuck-you-Ankita.m3u Fuck-you-Ankita.json"
