name: Run Python Script

on:
  schedule:
    
    - cron: "0,40 0-23/2 * * *"
    # Pattern 2: Run at minute 20 during odd hours
    - cron: "20 1-23/2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4

      - name: Unzip AES-256 Protected Files
        env:
          ZIP_PASS: ${{ secrets.ROARZONE_ZIP_PASSWORD }}
        run: |
          # Step 1: First layer extract (roar.zip -> inner roar.zip)
          7z x roar.zip -p"$ZIP_PASS" -y

          # Step 2: Second layer extract (inner roar.zip -> python files)
          # Note: inner roar.zip extract korle 'src' folder ber hobe
          7z x roar.zip -p"$ZIP_PASS" -y

      - name: Run script
        run: python src/main.py

      - name: Commit and push if it changed
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update playlist outputs"
          add: "Fuck-you-Ankita.m3u Fuck-you-Ankita.json channel_map.json"
